refactor: Update Azure deployment workflow for provisioning and deployment steps

diff --git a/.github/workflows/azuredeploy.arm.yml b/.github/workflows/azuredeploy.arm.yml
--- a/.github/workflows/azuredeploy.arm.yml
+++ b/.github/workflows/azuredeploy.arm.yml
@@ -37,8 +37,24 @@ jobs:
       - name: Get Azure Static Web App deployment token
         id: get-token
         run: |
+          echo "Fetching STATIC_WEB_APP_NAME..."
           STATIC_WEB_APP_NAME=$(az deployment group show --resource-group ${{ secrets.HELLOWORLD_RESOURCE_GROUP_NAME }} --name staticWebAppDeployment --query "properties.outputs.staticWebAppName.value" -o tsv)
+          echo "STATIC_WEB_APP_NAME: $STATIC_WEB_APP_NAME"
+          
+          if [ -z "$STATIC_WEB_APP_NAME" ]; then
+            echo "Error: STATIC_WEB_APP_NAME is empty"
+            exit 1
+          fi
+          
+          echo "Fetching TOKEN..."
           TOKEN=$(az staticwebapp secrets list --name $STATIC_WEB_APP_NAME --resource-group ${{ secrets.HELLOWORLD_RESOURCE_GROUP_NAME }} --query "properties.apiKey" -o tsv)
+          echo "TOKEN: $TOKEN"
+          
+          if [ -z "$TOKEN" ]; then
+            echo "Error: TOKEN is empty"
+            exit 1
+          fi
+          
           echo "token=$TOKEN" >> $GITHUB_ENV
           echo "staticWebAppName=$STATIC_WEB_APP_NAME" >> $GITHUB_ENV
       
